### ISSUE TITLE
Give episodes default release day of week and time.

### ISSUE THREAD

**Issue by drake1701** [firesidelabs/fireside-features#1]
It’s a small thing, but our show always releases at the same time 1 week from recording, it would be handy to have those dropdowns auto-selected.

Alternatively, giving shows a release queue would accomplish the same goal.

**Comment by dan** [comment]
What do you mean by "release queue"? Currently, you can set the publish date ahead of time, for as many episodes as you'd like.

**Comment by drake1701** [comment]
The queue would be more difficult to implement, and probably more niche use case, but if you had a show you release every Tuesday at 3pm, you would just put new episodes in a queue instead of setting that date/time explicitly. It's more for the (likely uncommon) case where a show records more than one episode in advance.

**Comment by dan** [comment]
I think I understand. Are you suggesting the pre-filled dates would be the same day of the month, every month? Can you give some examples?

**Comment by drake1701** [comment]
Sort of like alarms in iOS or other calendar recursion systems, or crontab syntax for that matter.

Weekdays at 8pm
Fridays at 5pm
Second Tuesday of the month at noon

**Comment by dan** [comment]
I'll mark this as a maybe. Thanks!

**Comment by jonathanbloom** [comment]
Kind of like how I've seen it, where you say "Release next day of the week, like the next Monday.
