### ISSUE TITLE
Blog - Ability to Use Header Image at Top instead of Podcast logo

### ISSUE THREAD

**Issue by jamesmontemagno** [firesidelabs/fireside-features#100]
Would be really great to have the ability to use the Header at the top of the blog instead of the podcast graphics. An example of one of our reviews: https://www.nintendodispatch.com/articles/review-little-nightmares-for-nintendo-switch a lot is below the fold.

**Comment by dan** [comment]
Neat idea.

**Comment by jamesmontemagno** [comment]
I think now it shows up! However, there is text overlay on top of it with the podcast name and such.

**Comment by dan** [comment]
This can be changed now in Appearance.
