### ISSUE TITLE
Add an option to combine title and subtitle in RSS feed

### ISSUE THREAD

**Issue by okken** [firesidelabs/fireside-features#101]
Current situation looks great on the website, but not that searchable within iTunes and other podcast clients.

Request: Combine title and subtitle for the RSS feed.

So instead of `<title>Test & Code</title>`
we get `<title>Test & Code - A Podcast about Software Testing, Software Development, and Python</title>`

This little tweak would increase the find-ability of mine and a lot of other podcasts, and still make them look good on the website.

**Comment by okken** [comment]
@dan Any thoughts on this? possible timeline? Can I help?

**Comment by dan** [comment]
I won't be adding this feature, but you can always change the title of your podcast to reflect this.
