### ISSUE TITLE
Reduce unsightly widows

### ISSUE THREAD

**Issue by russellquinn** [firesidelabs/fireside-features#103]
Certain description lengths and/or browser widths cause prominent text areas to wrap in a way that pushes the final word onto the next line, leaving things looking unbalanced (widows). Automatically inserting a `&nbsp;` character, at the presentation layer, between the last and second-to-last word would help this a lot.

<img width="1023" alt="screen shot 2019-01-24 at 10 19 51 am" src="https://user-images.githubusercontent.com/116075/51699847-91199480-1fc2-11e9-9abc-6cc02979d99d.png">

**Comment by dan** [comment]
We cannot do this automatically for you, but you're free to insert any non-breaking spaces you'd like in any location you'd like!
