### ISSUE TITLE
Option to hide list of episodes at the bottom of the Hosts page

### ISSUE THREAD

**Issue by russellquinn** [firesidelabs/fireside-features#104]
It would be nice to have an option to hide the list of episodes at the bottom of Host pages, if — like most podcasts — all hosts appear in all shows.

**Comment by dan** [comment]
Episode listings for individuals are there for a number of reasons, and provide a nice way for listeners to subscribe to their favorite hosts. It also helps with your SEO. Sorry but we won't be adding this feature. Hope that's ok.
