### ISSUE TITLE
Additional Social Links

### ISSUE THREAD

**Issue by jamesmontemagno** [firesidelabs/fireside-features#109]
Would love to have some additional social links:

* Patreon
* Twitch
* GitHub

**Comment by Scootronic** [comment]
Would like as well. If we could add bandcamp, wikipedia, and imdb as well.

**Comment by dan** [comment]
Patreon URL is already there (has been for a long while), the others roll out today.

**Comment by Scootronic** [comment]
Would you want a separate request to have this for the guests / hosts as well? in addition to fb, twitter, IG, linkedin, and Youtube? @dan
