### ISSUE TITLE
Youtube addition to rss/podcatcher bar for YouTube Show Playlist links

### ISSUE THREAD

**Issue by AngelaFisher** [firesidelabs/fireside-features#111]
I would like to see either a customizable field here that we would add and name and/or at a minimum "YouTube" added as a possibility under this section. In the social media area we would have "Jupiter Broadcasting" primary channel linked to and that makes sense.  In this particular case because our show BSD Now is video, I'd like to link to the YouTube playlist in this section for those that prefer to watch while keeping the social media area a link to the general YouTube channel.

Thanks!

**Comment by AngelaFisher** [comment]
I have since discovered that two of use were adding those links at the same time and may contributed to lack of saving URLs.  Please only consider the feature I've requested.

**Comment by dan** [comment]
Angela,

YouTube is listed under the Social Networks section, and appears on the main page, along with the other social networks.

-Dan

**Comment by AngelaFisher** [comment]
Yes I understand and the social network area is where I have the Jupiter Broadcasting YouTube linked. I'm asking for a YouTube option in the bar that would be a link to the individual show playlist. 
![yt playlist link](https://user-images.githubusercontent.com/44704851/53651551-bf127a00-3bfb-11e9-895f-bd11eaf014c2.png)

**Comment by dan** [comment]
Unfortunately I'm going to have to deny this. YouTube isn't a podcast player or podcast service like the others.
