### ISSUE TITLE
Episode Descriptions missing from dark themed shows

### ISSUE THREAD

**Issue by AngelaFisher** [firesidelabs/fireside-features#113]
I cannot figure out why the description for each show is not appearing on the landing page for some of our shows. For example: https://www.bsdnow.tv/ only shows tags, no description. I have combed the settings as well as compared shows that do show the descriptions like: https://techsnap.systems/. Is it a limitation of the dark theme format? Thanks for any guidance.
![no episode description](https://user-images.githubusercontent.com/44704851/53602490-d0a84300-3b63-11e9-99fb-ec89a4b1dd54.png)
![episode description](https://user-images.githubusercontent.com/44704851/53602491-d0a84300-3b63-11e9-8403-8a2fb7430ce6.png)

**Comment by dan** [comment]
This should be a ticket, not a feature request. Please file a ticket instead. Thanks!

I'm closing this for you.
