### ISSUE TITLE
Request: Feed item limit

### ISSUE THREAD

**Issue by theDanielJLewis** [firesidelabs/fireside-features#119]
Choose to limit the feed to fewer episodes.

When I migrated an old feed (with 266 episodes), the old feed was using FeedBurner as only a feed mirror (none of the features turned on), but I couldn't easily switch to the Fireside feed because it was bigger than FeedBurner's 1 MB limit. So I had to do some sneaky switching around that could have been much easier if I could have lowered the feed item limit temporarily until I could delete and redirect the FeedBurner feed.

**Comment by dan** [comment]
This doesn't have to do with Fireside, as there is no limit on the number of episodes that can be imported. Perhaps you could suggest this to Feedburner.

**Comment by theDanielJLewis** [comment]
But I think there is a potential need or desire for someone to limit the number of items in their feed, especially if they have a current-events-related podcast. So if someone published 1,000 "daily news" episodes, it seems they don't have any way of limiting the feed to display only the last 50 (or whatever limit they desire).

**Comment by dan** [comment]
Oh I see, you're *asking* for Fireside to be able to limit the number of items in a feed?

**Comment by theDanielJLewis** [comment]
Yes. I'm sorry I didn't communicate that better.
