### ISSUE TITLE
Adding Radio Public for subscribing

### ISSUE THREAD

**Issue by alteredoutlook** [firesidelabs/fireside-features#12]
Radio Public has become popular with small niche style podcast, I was wondering if we could add a subscribe option for them?

**Comment by dan** [comment]
Can you provide a URL for Radio Public and an example of what you'd like to see?

**Comment by jonathanbloom** [comment]
[Here is an example of RadioPublic](https://play.radiopublic.com/be-great-today-weekly-inspiration-G3VDp2). They have an app and web player eco-system that they have been building.

**Comment by dan** [comment]
I was hoping for an example of a subscribe link on a podcast website.

**Comment by jonathanbloom** [comment]
Here's one. https://www.sleepwithmepodcast.com/689-mars-moranis-curry-seltzer-pitching-roman/

**Comment by dan** [comment]
Done.
