### ISSUE TITLE
Request: Find and replace (better with regex)

### ISSUE THREAD

**Issue by theDanielJLewis** [firesidelabs/fireside-features#121]
For easily removing stuff from all episode descriptions, show notes, titles, or author tags. For example, your episode numbering and title system seem great, but our episodes already have the numbers in them with an abbreviation like " - BTTDL044." So a regex search for "\s-\sBTTDL\d{3}" would easily clean that up.

**Comment by dan** [comment]
Neat idea, but I won't be implementing this in the near term.
