### ISSUE TITLE
Request: <itunes:new-feed-url>

### ISSUE THREAD

**Issue by theDanielJLewis** [firesidelabs/fireside-features#122]
For thorough migrating from old feeds, this tag in the new feed is the fastest way to make Apple Podcasts and several other podcast apps permanently switch, even when the original feed is 301-redirecting.

[Apple even recommends using both the 301 on the old feed and `<itunes:new-feed-url>` on the new feed.](https://help.apple.com/itc/podcasts_connect/#/itca489031e0) And Libsyn has reported noticeable migration speed improvements in Apple Podcasts when this tag is added on the new feed.

Yes, it may seem redundant, but it's really a kind of confirmation that Apple Podcasts (and some other apps) have arrived at the correct feed.

**Comment by dan** [comment]
Question for you: how would Fireside be smart about knowing when to add this? Sure, we could make it a checkbox, but it's likely most customers would either miss it or not understand its purpose, or worse: add it when it's not necessary. And unfortunately there's no way for Fireside to intelligently "just know" when to add it.

Open to your suggestions!

**Comment by theDanielJLewis** [comment]
It could be a simple checkbox, like "Check here you're redirecting an old feed to your Fireside feed," and the information popup can explain what it's doing. Checking that box would enable `<itunes:new-feed-url>` and point to itself, per Apple's instructions.

So then there's no confusion or chance of putting in the wrong thing.

**Comment by dan** [comment]
Meant to update this - Fireside began intelligently adding this tag as needed for imported podcasts for the Apple recommended time period.
