### ISSUE TITLE
Stats: Show number of downloads per continent

### ISSUE THREAD

**Issue by khiddy** [firesidelabs/fireside-features#124]
I'd like to be able to see how many downloads my show gets on the various continents, and total downloads for the countries on the particular continent. I can select individual countries from the drop-down and see the distribution of downloads within them (e.g., "100% of your downloads in Austria were in Vienna"), but I would like see what they all add up to on a per-continent and per-country basis, in terms of a number of downloads or a percentage of all downloads (e.g., "This episode has been downloaded 234 times in Nigeria.") Thank you for the great support so far!

**Comment by dan** [comment]
Cool suggestion. We might make this part of the Pro version of Stats, or maybe the normal one.

**Comment by dan** [comment]
Could you add this suggestion to our community topic about Stats?

https://fireside.zendesk.com/hc/en-us/community/posts/360034815774-Pro-Plan-Stats-Features
