### ISSUE TITLE
Add Castbox to the List of Podcast Aggregators?

### ISSUE THREAD

**Issue by robotcaveman** [firesidelabs/fireside-features#125]
I have recently gone through the process of adding my show to Castbox’s ’Editor’s Picks’ list, and one of their steps is to link to their page from our home site. I currently have it as a custom link in the top menu bar, but it’d be nice to be able to add them in with the other podcast aggregators list. Would it be possible to add that as a feature? Thanks!

**Comment by dan** [comment]
Done.
