### ISSUE TITLE
Background Images on the individual Host/Guest pages.

### ISSUE THREAD

**Issue by Scootronic** [firesidelabs/fireside-features#126]
For exmaple: https://www.geekcoreradio.com/guests/kirbykrackle . Have the background image, behind the profile image, be uploadable for Hosts and Guests (several guests for this show requested this to distinquish themselves more.

**Comment by dan** [comment]
Neat idea, but we won't be adding this in the near-term. Sorry about that.

**Comment by Scootronic** [comment]
No worries. If this falls into the design in the future would love it (several guests have requested it)
