### ISSUE TITLE
Host/Guest: Custom titles for the category to display as

### ISSUE THREAD

**Issue by Scootronic** [firesidelabs/fireside-features#127]
For example on: https://www.geekcoreradio.com/guests/. I'd like the title at the top that says "Guests" to say "Featured Artists". I'd love it if that could change all places that guest is mentioned (on the lap that appears at the top of the website (I turned it off and put a custom link to get a similiar feel), and on each episode where it lists guests, have it say this label instead.

Same for hosts. Page name could be the same (for the url), but just a different label that gets dynamically filled in based on a configuration we can set on the admin.

**Comment by dan** [comment]
This will be supported in a coming update.
