### ISSUE TITLE
When Changing Podcasts, stay on the same relative page

### ISSUE THREAD

**Issue by Scootronic** [firesidelabs/fireside-features#128]
When clicking on the drop down to switch to another podcast, it would be nice if we could remain on the same relative page (or at least section). So if I'm in Stats, at least take me to the main page of stats (that might work better, because the main page should exist on each show regardless of any customization).

**Comment by dan** [comment]
Neat idea, but for now the drop down will still take you to the main Dashboard page to reduce confusion and eliminate the many edge case conditions this would create. 

Sorry about that!
