### ISSUE TITLE
Network - Joined RSS Feed and Pages.

### ISSUE THREAD

**Issue by Scootronic** [firesidelabs/fireside-features#129]
When podcast networks are set up and available, can we have a unified RSS feed? That basically combines the records from all of the rss for each podcast to create a new rss? I'd like this so that we could submit a separate "Podcast" for our network. If people would like to keep up to date with whatever shows are in the network, then all they need to do is subscribe to the network's podcast page.

Same would be good for, episodes, Hosts, Guests, and some behind the scenes stuff like stats and sponsors.

**Comment by dan** [comment]
This is part of the Network feature, coming soon.
