### ISSUE TITLE
Ability to specify an image for Sponsor and display on website only

### ISSUE THREAD

**Issue by jamesmontemagno** [firesidelabs/fireside-features#13]
Right now we have to upload an image for the sponsor and then use markdown to put it in the page.

This works great for the website, but it doesn't show up in podcast apps and just shows ugly markdown :(

Ideally would be nice if the sponsor can have an image that links to their url that we specify and that it only shows up on the website.

**Comment by dan** [comment]
I agree, but I don't plan to do any work on the Sponsors feature at all.

I had added it during beta and meant to remove it. It was poorly thought through and poorly implemented, and I'm embarrassed of it. It's the only feature in Fireside that I regret building and I'm not proud of it.

Almost nobody uses it, but I'm loathe to remove a feature that people are using. That said, I don't plan to change or improve it in any way, and soon, new customers (and customers who aren't using it already) won't see it anymore.

Sorry!

**Comment by jamesmontemagno** [comment]
@dan gotcha, that makes sense and I appreciate you getting back to me. Would be curious if others are using it at all or how they manage their sponsors. Overall I am pretty happy with it besides a few tweaks here and there. Would be interested in a re-imagining or maybe a survey of what everyone is looking for.
