### ISSUE TITLE
Entries for producer, editor, music, etc

### ISSUE THREAD

**Issue by jasonian** [firesidelabs/fireside-features#132]
A podcast I produce/edit thanks me at the end, and they want to list me on their show page, but there’s no way to add me except as either a “host” or a “guest”.

A way to add people who work on the show would be nice. (Even small shows like the one I work on probably have people to credit.)

I would imagine this would be an open entry field, with a few standard options (like Producer, Editor, Engineer, Music...), with options that are “episode specific” and “show wide”.

Credits may show up on the About the Show page and the episode page, and perhaps on a “Staff” or “Credits” page (like “Hosts” and “Guests”).

**Comment by Scootronic** [comment]
I would love to see this too.

**Comment by dan** [comment]
Neat idea, why not add it to the description? You can also create a Default for this so it'll appear on every new episode so you won't have to retype it?

**Comment by Scootronic** [comment]
For Audio Dramas at least this could change from episode to episode. Plus it would be nice if someone could pull up a list of Engineers specifically, like they can guests, or Directors, or whatever.

**Comment by Scootronic** [comment]
I think I'm leaning towards the direction that they go for IMDB or the like. Maybe the solution wouldn't be different buckets to put people in. But on episodes being able to assign them roles when associated with the episode. So when you look at their "guest" profile it will not just show what episodes they were featured in, but what the role they had was (also like IMDB lite) @dan

**Comment by jasonian** [comment]
Hi @dan, can you explain why you closed this request? Not sure if it's because it's not feasible or something else.

**Comment by Scootronic** [comment]
We do have it in the description. It would be nice under the "guests"
profile for it to indicate what roles they had on which episodes, not just
that they were in it.
