### ISSUE TITLE
Embeddable Web Player for Social Media and Web

### ISSUE THREAD

**Issue by albert-park** [firesidelabs/fireside-features#133]
As a person who is marketing their show, I would like an embeddable player that can be embedded on to other platforms, web pages, and social media posts. This will get more earballs on the episodes, as well as be a branding opportunity for Fireside.

**Comment by albert-park** [comment]
may be related to [this request](https://github.com/firesidelabs/fireside-features/issues/117)

**Comment by dan** [comment]
This exists, just click the Share link on the Episode's public page or the Share tab on the Episode's Admin page.
