### ISSUE TITLE
Request: WordPress integration? 

### ISSUE THREAD

**Issue by marthap123** [firesidelabs/fireside-features#137]
This might be a reach but it would be helpful if Fireside had a feature for show notes so you could publish it as a blog post to Wordpress.

* Map [Title of Episode] to Wordpress Blog Post Title 
* [Description] maps to body of blog post, etc. 

(ie essentially a Zap a la Zapier, if WordPress integration is not ideal then perhaps a push to Google Sheets with episode details as a spreadsheet to connect to Zapier)

**Comment by dan** [comment]
@marthap123 I've added the ability to export the notes. Although there's no way to auto-submit them to a third party as you've suggested, it could be done manually.
