### ISSUE TITLE
Links should open up in a new tab, not the current one.

### ISSUE THREAD

**Issue by Scootronic** [firesidelabs/fireside-features#138]
Currently when clicking on a link to something outside of the website (say the links for the different subscribe options, or under Host and Guests) they go to that within the same tab. It would be nice if they opened a new tab. (Since while people may be interested in that, it takes it outside of the show's podcast page.)

**Comment by chrisgherbert** [comment]
Forcing a link to open in a new tab removes control from the user. It can also confuse people who don’t use tabs, because their back button no longer works.

**Comment by dan** [comment]
@chrisgherbert's comment is accurate. Any time you remove a visitor's ability to choose, you're creating a bad user experience. Sorry about that.
