### ISSUE TITLE
Request: Built In Spellcheck for New Episodes, Blogs, Pages, etc

### ISSUE THREAD

**Issue by GeekHerring** [firesidelabs/fireside-features#139]
It would be beneficial for us if there was a spellcheck built in when creating show notes, blogs, pages, etc -- just to help! I don't spell a lot of things wrong, but things do come up and I'm like - ah, no - totally missed that! Thanks for the consideration :)

**Comment by dan** [comment]
The spell-checkers that are now built into web browsers on desktop and mobile platforms would make a feature like this redundant. Sorry about that!
