### ISSUE TITLE
Ability to re-order all pages (including built-in)

### ISSUE THREAD

**Issue by jamesmontemagno** [firesidelabs/fireside-features#14]
Right now we have control over each sub-section, but not full control over the full order our the pages in the nav. Would be nice to have one UI where we can drag and drop the navigation.

**Comment by dan** [comment]
Do you mean change the order of the built-in pages as well as the Custom Pages?

**Comment by jamesmontemagno** [comment]
That would be the idea. Essentially full control over the ordering of the navigation. Right now all 3 sections (built-in, custom pages, custom links) can be controlled separately, but not together.
