### ISSUE TITLE
Email digests

### ISSUE THREAD

**Issue by therealchadhall** [firesidelabs/fireside-features#141]
This is a real pie in the sky request but it would be incredibly useful to receive an email at the 1, 7, 14, 30, and 90 day milestones with the episode download numbers. Doesn’t have to be full analytics because obvious those are available at the site but something simple like “It’s been 14 days since you published episode 104. It has been downloaded 2349 times. Congrats.”

It also occurs to me that this need not necessarily be an email, an rss that can be feed into slack would work as well. I request this as a way to keep teammates up to date and encouraged without giving everyone access to the account.  Perhaps you can think of a more elegant solution.

**Comment by dan** [comment]
Interesting idea!

**Comment by david-linssen** [comment]
Slack integration, anyone?
