### ISSUE TITLE
Metrics-only Collaborators Role

### ISSUE THREAD

**Issue by chrisgherbert** [firesidelabs/fireside-features#142]
It would be great to have a "read only" collaborator role that only allows access to metrics, and doesn't allow the user to change anything.  This would be good for marketing partners who need access to the stats but do not need to actually create/update/delete episodes.

**Comment by dan** [comment]
I think the share page under the sponsors tab could be used for this task in the meantime.

**Comment by chrisgherbert** [comment]
Is that under the "sponsors" page in the admin backend?

**Comment by dan** [comment]
It is.
