### ISSUE TITLE
ER: Make "Simple Sharing Page" available user custom domains

### ISSUE THREAD

**Issue by jasonian** [firesidelabs/fireside-features#143]
The "Simple Sharing Page" link is handy for sharing to Twitter and Facebook. I'd like to be able to brand those with my custom domain. So, for example, instead of

https://fireside.fm/s/ohvSM0D_+RBq6P1_Z

it would be

https://www.lettucewrappod.com/s/ohvSM0D_+RBq6P1_Z

**Comment by dan** [comment]
We won't be changing how the Simple Sharing Page works at this time, but I would consider an additional page for custom domain users. Thanks for the suggestion.

**Comment by david-linssen** [comment]
would be greatly appreciated from a branding perspective
