### ISSUE TITLE
Metrics - view breakdown of episode downloads in a given time period

### ISSUE THREAD

**Issue by rozerosie** [firesidelabs/fireside-features#144]
I'd like to be able to see a download count per episode in a given time period (by month, for example).

I pull marketing metrics for our most popular pieces of content, across a number of content channels; I'd like to be able to pull and compare monthly metrics for individual episodes of our podcast alongside our blog, youtube, etc. Basically I want to be able to answer the question "what was our most downloaded podcast episode last month (or some other time interval)? how many downloads did it get?"

**Comment by dan** [comment]
This is a great suggestion, and something I'd like to add to the Advanced Stats that will be part of the upcoming Pro plan.

I've created a Topic in our new community forum. If it's not too much trouble, would you mind adding your comment there?

https://fireside.zendesk.com/hc/en-us/community/posts/360034815774-Pro-Plan-Stats-Features
