### ISSUE TITLE
Feed for Internal Reviews

### ISSUE THREAD

**Issue by garethryan** [firesidelabs/fireside-features#146]
setup two feeds. One that requires authentication for internal stakeholder review Pre-Release and another that is for Public release.

**Comment by garethryan** [comment]
Do we have an update on whether or not this is feasible?

**Comment by dan** [comment]
Features like this will be associated with Phase 2 of User Roles, which is coming as part of the Pro plan.

**Comment by garethryan** [comment]
Thanks @dan!
