### ISSUE TITLE
Option(?) to not count downloads from the Preview page in metrics 

### ISSUE THREAD

**Issue by jasonian** [firesidelabs/fireside-features#148]
There's the ability to stage an episode days or weeks ahead of release, and preview that page to see how it looks.

If you play an episode from a preview page, it counts as a download in metrics.

This messes up the "First X Days" metrics, as the downloads start earlier than the episode is released.

This request is to not count the downloads that happen from a Preview page in the metrics, under the logic that an downloads should only count after the app has been released to the public.

The metrics page itself does not display an episode in the list until after the episode has been made public, so there's some precedent for when metrics "matter".

There are a couple of alternatives that might be considered instead:

1. Show the episode in the metrics list before it's released. This would be consistent with the fact that downloads are counted, and so should be shown in the metrics page.

2. Provide an option to show metrics from "first download" or "first day public" that would appropriately adjust the display of the metrics.

A similar request was filed (and subsequently closed) but I'm hoping this can be reconsidered.
https://github.com/firesidelabs/fireside-features/issues/97

There's a related request to count metrics that are in unlisted episodes already filed.
https://github.com/firesidelabs/fireside-features/issues/132

**Comment by dan** [comment]
Done.
