### ISSUE TITLE
Subscribe by Email support

### ISSUE THREAD

**Issue by jonathanbloom** [firesidelabs/fireside-features#15]
I would love to be able to add a button to allow someone to add the show to Subscribe by Email.

http://subscribebyemail.com/

Here's an example of what it looks like. http://subscribebyemail.com/be-great.today/rss

**Comment by mfessler** [comment]
Agreed - I have boilerplate text in every episode's notes with the link to do this.

**Comment by dan** [comment]
Why not paste this into your subscribe page?

**Comment by jonathanbloom** [comment]
Added those to the Subscribe page.
