### ISSUE TITLE
Clicking an episode in the bar graphs displays episode details. 

### ISSUE THREAD

**Issue by ChrisOOS** [firesidelabs/fireside-features#150]
When looking through the bar graphs, hovering over the bar graphs displays episode number and number of downloads (which can already be ascertained). It would be great if the hover or a click revealed more information about the episode. Maybe not as detailed as the screenshot attached, but even the episode title, date and duration would be useful to answer quick little questions without having to navigate away from the page. 

Thanks for the consideration!
![fireside_metrics_popup_feature](https://user-images.githubusercontent.com/1719981/62000100-7cb37300-b09d-11e9-8de0-4d5b0c7e1a05.jpg)

**Comment by dan** [comment]
I wish we had that kind of customization capability with the graphing library we're using. Alas, it's not available, and adding something like that would require completely scrapping our entire stats display layer and rebuilding it with something that can offer this feature ... assuming it even exists!

A great suggestion, but not something we can do right now. Thank you!
