### ISSUE TITLE
Subscribe on Android support

### ISSUE THREAD

**Issue by jonathanbloom** [firesidelabs/fireside-features#16]
Would like to be able to add a Subscribe on Android button. The site has worked with different app developers to make Android subscription simple.

http://subscribeonandroid.com

Example: http://subscribeonandroid.com/be-great.today/rss

**Comment by dan** [comment]
Would you not be able to just paste this into your Subscribe page?

**Comment by jonathanbloom** [comment]
Added those to the Subscribe page.
