### ISSUE TITLE
Metric: compare first X days' downloads across episodes in /admin/metrics

### ISSUE THREAD

**Issue by mfessler** [firesidelabs/fireside-features#2]
A) It would be great to be able to compare the first X days' downloads across episodes,  so we can see "how did these episodes compare in the first 7/30/90/365 days?" Right now, the show-wide view in /admin/metrics shows current download counts, but it would be great to able to compare episodes across similar periods of time where possible. 

B) On a related note, I see that the individual episodes' stats pages do show the totals for All Time/7/30/90/365 days. However, you can only see them by mousing over the last data point in the relevant chart. Could you also display the number for the time period you're looking at? We see the overall total and today's total at the top - could "currently selected span's total" be beside or below them? 

C) Finally, just a question - is there a reason that show-wide info is called "metrics," but on an individual episode level, the heading is "stats"? 

Thanks so much!

**Comment by dan** [comment]
C. In many fields, the term "metrics" refers to a comparison of things, where "stats" is a measurement of a specific things. So I ran with that.

**Comment by ecec** [comment]
I know you're working on Stats 2.0, so I figured here would be a good place to put feature requests for that. 

- I'd love to have an overview page, that shows me a list of my episodes, with columns for the first 1/7/30/365 day metrics. Basically what mfessler is describing above in (a)

- I'd like to be able to define a date range and see (1) total downloads in that period (2) a list of episodes that had downloads in that period ordered by most downloads to least and (3) where those downloads came from in that period.
