### ISSUE TITLE
App icons instead of +

### ISSUE THREAD

**Issue by mrfoto** [firesidelabs/fireside-features#20]
We have icons for RSS, Apple Podcasts, Google Play, and Spotify so it would make sense to have it for others as well. It would definitely look nicer and more consistent.

If you're using premium version of Font Awesome they already provide that option: https://fortawesome.com/start

Otherwise you could do it with http://fontello.com/

**Comment by dan** [comment]
Thanks for the idea. We might make this change at some point.
