### ISSUE TITLE
More Control Over Podcast App Links

### ISSUE THREAD

**Issue by jamesmontemagno** [firesidelabs/fireside-features#21]
Today the Podcast App Links are on every page and also on http://www.mergeconflict.fm/subscribe

However as more and more apps add podcast it may get a bit crazy.

Ideally we could have the option to say which items are on every page with a "more" option that would go to the subscribe page that show all of the possible apps. Additionally, being able to modify this page would be nice too.

**Comment by dan** [comment]
You could manually add links to your subscribe page, and just not put them in the settings. Would that help?

**Comment by jonathanbloom** [comment]
I did that part after finding out I could, it just might be nice to be able to add additional links, or based on your device. This might be more sophisticated than possible at this point without redesigning the Links system.
