### ISSUE TITLE
Contact Form ReCaptcha

### ISSUE THREAD

**Issue by jonathanbloom** [firesidelabs/fireside-features#24]
I've been getting periodic spam comments on the show contact form. Can we get the option to have ReCaptcha added?

**Comment by dan** [comment]
Possibly - we cannot add a recaptcha for sites that don't use a fireside.fm subdomain because of the restrictions they place.

Unlike google analytics, the recaptcha has to be integrated into the code of the site, so it's not a cut-n-paste your code type of solution.

**Comment by vallieres** [comment]
Perhaps implementing a honey pot might help with the spam? I got so many of it that I basically removed the form. I understand the limitations of custom domains, but a honey pot can be a good way to reduce dramatically the number of spam emails.
