### ISSUE TITLE
When episode title is supposed to be "Episode X:" prepended, do so on episode page header too

### ISSUE THREAD

**Issue by mfessler** [firesidelabs/fireside-features#28]
If we check the box that makes Fireside prepend "Episode 3:" (or whatever) to your episode name, it shows up that way in the episode list - but not on the individual episode page in the header/player.

Seems as if this should at least be an option.

![screen shot 2018-05-14 at 5 26 51 pm](https://user-images.githubusercontent.com/876795/40024358-0d761624-579c-11e8-9b23-7be346bf7ff5.png)
![screen shot 2018-05-14 at 5 26 55 pm](https://user-images.githubusercontent.com/876795/40024359-0d851480-579c-11e8-85d8-42c7948ca0dc.png)

**Comment by dan** [comment]
Done.
