### ISSUE TITLE
Metrics: Change Mapping for Clicks on Episode

### ISSUE THREAD

**Issue by Scootronic** [firesidelabs/fireside-features#29]
Currently: When clicking on an episode on the Metrics page, it links to the Details subpage for the individual episode.

Proposed: That link would be more useful if it linked to the Stats subpage for the individual episode.

Justification: If I'm poking around on the metrics page, if I click on the episode on the Metrics page, most likely I want to see the stats for that individual episode.

**Comment by dan** [comment]
Excellent. Done and deployed.
