### ISSUE TITLE
Metrics: Being able to Filter the Entire Metrics Page

### ISSUE THREAD

**Issue by Scootronic** [firesidelabs/fireside-features#30]
Currently: The metrics page is static

Proposed: Allow specific things that the entire metric page could be filtered down to. Either done with something like drop downs or being able to click on the existing words on the metrics page select what you want to filter by. Suggested filters could start with: Country(maybe region too?), Operating Systems, Point of Origin(Apps maybe?)

**Comment by dan** [comment]
Nice suggestions, I'll consider this as we continue working on Stats v2!
