### ISSUE TITLE
Button for transcripts is missing "Preview" text that used to be there - empty button.

### ISSUE THREAD

**Issue by mfessler** [firesidelabs/fireside-features#33]
See above and attached.

![screen shot 2018-05-23 at 6 05 19 am](https://user-images.githubusercontent.com/876795/40418113-7b4d4fb4-5e4f-11e8-9179-55eeea70eb9c.png)

**Comment by dan** [comment]
Fixed.

**Comment by mfessler** [comment]
Still looks the same to me. 
![screen shot 2018-06-07 at 3 40 00 pm](https://user-images.githubusercontent.com/876795/41122316-2222a5b2-6a69-11e8-9a9e-887f89de61e8.png)
