### ISSUE TITLE
Please Add itunes:keywords

### ISSUE THREAD

**Issue by jamesmontemagno** [firesidelabs/fireside-features#36]
I am begging you to please add the keywords tags to the RSS feed. There are many podcast applications that use this to determine their search algorithms such as player.fm: 

Nintendo Tags: https://player.fm/featured/nintendo

Tags show up here: https://player.fm/series/nintendo-voice-chat-20913

Please please please please please please please add these.

**Comment by dan** [comment]
It's unfortunate that third parties rely on something that iTunes has asked us to remove. I'm not sure that adding it back would be copacetic with Apple, but it's something I can investigate.
