### ISSUE TITLE
Search should search through episode links

### ISSUE THREAD

**Issue by gcluley** [firesidelabs/fireside-features#43]
Title says it all. :)

I was trying to find a particular episode, where I had put in a particular link about something.  For clarity, I'm not suggesting search be extended to look through the actual URLs, but rather the titles that we give those URLs.

Thanks

**Comment by dan** [comment]
This is a good suggestion. I'm on the fence about it for a few reasons:

1. Many people do not create titles with as much care as others, often leaving the standard title. This would create poor search results.
2. There are often dozens of links in each episode. Indexing these links would create a huge overhead and a whopping performance hit, but with very little return.

I'm going to continue to think about this, but I don't know if or when I'll be implementing. Sorry about that!
