### ISSUE TITLE
Add Ability to Attribute Blog Posts to Specific Host

### ISSUE THREAD

**Issue by robotcaveman** [firesidelabs/fireside-features#45]
Hi, my co-hosts and I would like to start using the blog feature on Fireside, and we were looking for a way to attribute specific blog posts by specific hosts, much like an author feature on most blogging platforms. A simple byline under the post title would suffice, but if the host’s name, bio and avatar could also be appended at the end of the post that would be awesome. Thanks for looking into this!

**Comment by dan** [comment]
Done.
