### ISSUE TITLE
Add "Google Podcasts" to list of "Listen on..." services

### ISSUE THREAD

**Issue by gcluley** [firesidelabs/fireside-features#47]
We've got Apple Podcasts, Spotify, Castro, and everything else...

Lets have "Google Podcasts" too!  It's available on every Android device without needing an app to be installed, and is ideal for podcast newbies.  In fact, I'm considering ditching all the subscribe links apart from Apple Podcasts and (if you add it) Google Podcasts.

Google even provides the "Listen on Google Podcasts" graphic here:
https://developers.google.com/search/docs/data-types/images/google_podcasts_brand_assets.zip

Cheers

**Comment by dan** [comment]
Is this different from Google Play? Same thing with a new/different name?

**Comment by gcluley** [comment]
This article also discusses some of Google Podcasts's benefits to podcasters trying to increase adoption amongst Android users:

https://medium.com/@JamesCridland/why-the-new-google-podcasts-app-is-a-big-deal-and-why-there-are-no-auto-downloads-9eb2cc0d2f66
