### ISSUE TITLE
Add https support for custom domains

### ISSUE THREAD

**Issue by timmmmyboy** [firesidelabs/fireside-features#48]
Ideally automatic with Let's Encrypt but even the option to upload an SSL cert of our own would be great.

**Comment by dan** [comment]
Already coded and in beta testing. The amount of infrastructure required for this at the level we're at is massive, and there's lots and lots of code, servers, and testing which makes this particular feature take a long while.

**Comment by dan** [comment]
Done, as I'm sure you've seen!
