### ISSUE TITLE
Add YouTube Integration to Subscribe Page

### ISSUE THREAD

**Issue by matrda42** [firesidelabs/fireside-features#49]
As a video podcast who primarily uses YouTube to promote my show and a show that uses fireside to host my audio, I would love to have an option for users to have a button to click on like itunes, google play, stitcher have etc that would be a direct link to subscribe to the youtube channel for my podcast. I run my podcast off most audio podcast platforms but youtube is the main part of my show where viewers/listeners can see myself and the guest interact like most video radio shows. Currently I can only drop a link to my youtube which looks less appealing compared to the branded buttons that iTunes or other podcasts have in the subscribe section.

I've noticed that in the guest section for fireside, you can link the guests youtube channel in the form of a non branded button but still a button. Wondering if this can be made possible for YouTube.

Thanks

**Comment by dan** [comment]
The link under Social Networks in the Admin -> Settings -> General section will place a YouTube link to the URL you specify.
