### ISSUE TITLE
Smart Guests functionality

### ISSUE THREAD

**Issue by mrfoto** [firesidelabs/fireside-features#6]
Do not display Guests with 0 appearances. That way I can schedule a podcast beforehand and enter all the guest details without giving it away. And as soon as the podcast is published, the guest has more than 0 appearances and they would show up.

**Comment by mrfoto** [comment]
And just after going to Fireside I see this was added 😂️

**Comment by jamesmontemagno** [comment]
Seems like they still show up for us with 0 episodes... We have public episodes but scheduled for the future. https://www.trinspo.com/guests
