### ISSUE TITLE
Give the option to not add the artwork to the mp3 file

### ISSUE THREAD

**Issue by egla89** [firesidelabs/fireside-features#62]
This would disable the embedding of an artwork into the mp3 file on Fireside.com, as some are already using external tools like Forecast for that and prefer that.

**Comment by dan** [comment]
I'll consider this, but adding artwork (even episode specific artwork) is a deeply integrated feature of Fireside, and one of the benefits of using it.

**Comment by dan** [comment]
Done.

Details: https://fireside.fm/account/news/1e2f4d7c-3e2d-43d0-aae9-24fb5d918cc0
