### ISSUE TITLE
Allow users to select preferred date format or infer from their given location

### ISSUE THREAD

**Issue by bensmithuk** [firesidelabs/fireside-features#63]
At present the site presents dates in "Month Day, Year" format on episode pages and content listings. This is format is almost exclusively used in the US and 'feels wrong' to those of us where this is not normal.

The "Year Month Day Time" structure in the admin interface is fine and I do not propose this change affect that.

For reference, Wikipedia article on preferred date formats: https://en.wikipedia.org/wiki/Date_format_by_country

**Comment by dan** [comment]
Done.
