### ISSUE TITLE
Offer a Creative Commons alternative to the copyright footer

### ISSUE THREAD

**Issue by bensmithuk** [firesidelabs/fireside-features#65]
Allow publishers to choose a footer specifying their content is licensed under Creative Commons and to choose the type of license, if they prefer this form of licensing their content.

**Comment by dan** [comment]
And ... done.

https://fireside.fm/account/news/0939a6e5-fe6e-46de-ae27-c149f6e58b5f

**Comment by dkrushev** [comment]
Every time I open General Settings section, License Type is reverted to Standard Copyright. So every time I want to make a change in that section, I have make sure the License is changed as well, if I want to be anything else than Copyright.
