### ISSUE TITLE
Handle cover art provided as transparent PNG more elegantly

### ISSUE THREAD

**Issue by bensmithuk** [firesidelabs/fireside-features#66]
At present, PNGs with transparency are converted to JPEG with black replacing the transparent colour. There's no warning in the admin interface that this will happen.

I uploaded in this format because my logo is round and I wanted the transparency to be used in the website header. I assumed I would be able to choose a background colour for the places where that format can't be used.

**Comment by dan** [comment]
Ben,

Cover art is used by Fireside on the site, embedded into the MP3 file, and used by third parties such as iTunes. Most if not all third parties require JPG files, and if a non-JPG file is submitted, it will usually be converted to JPG anyway by the service, usually with questionable results.

For this reason, Fireside handles the conversion of all uploaded images to JPG.

And there's another reason: file size. PNG files tend to be 2 - 3x larger than JPG files, and cannot use image compression to reduce the file sizes. Perhaps this is why most services require or convert to JPG.

Anytime a PNG file is converted to a JPG, you will see "black replacing the transparent" colors in the image.

I wish I had better news for you, but we won't be making this change at this time.

-Dan

**Comment by bensmithuk** [comment]
@dan Noted and accept the reason for closure.

For background - I understand the need to convert the cover image for use in MP3 / 3rd part assets.

The request was motivated by trying to avoid the black background when shown on the website. In the end I made a new version of the cover image colour-matched to the 'minimal light' theme's light grey background, but of course I'll need to re-do that if we change theme or the it's updated in future. It's also a compromise because we have 7 years on white and a sudden mid-season shift to grey - that's probably only an issue for my OCD though :-)
