### ISSUE TITLE
More Control Over Episode # Frontend Presentation

### ISSUE THREAD

**Issue by Glark** [firesidelabs/fireside-features#68]
Currently, the only way to have FS add the episode # metadata for you is as part of the "title prefix" setting which adds "Episode X: " to the front end presentation (and maybe RSS feed?)

I'd like that episode metadata on our pages as we'll often refer back to episode X in later podcasts but we don't really want every episode title to start with that info.

It would be nice to be able to just set that info as another piece of the episode metadata, along with season #, date, etc. I added an example below but there's multiple templates that would need to be addressed of course.

<img width="365" alt="extra hot great 2018-09-14 14-06-55" src="https://user-images.githubusercontent.com/1977886/45974772-fefb8280-c007-11e8-9234-962ec8935c21.png">

**Comment by dan** [comment]
Neat suggestion, but seems a bit like an edge case right now. I'll wait and see if any other requests for this come in.
