### ISSUE TITLE
Display more links on the Simple sharing page

### ISSUE THREAD

**Issue by mrfoto** [firesidelabs/fireside-features#7]
Right now you only show RSS and Apple podcast links. I think it should show the same as the main page - so all that I define.

**Comment by dan** [comment]
The purpose of that page is to enable to share an episode on social media and have it render correctly.
If anything, I should remove the Apple Podcasts link and just show the RSS. I'll probably do that this week.

**Comment by dan** [comment]
I've made the change to remove apple podcasts.

**Comment by mrfoto** [comment]
Yeah, that’s even better solution - making the simple page even simpler 👌
