### ISSUE TITLE
Add Google Podcasts Distribution Field

### ISSUE THREAD

**Issue by Haddiebird** [firesidelabs/fireside-features#74]
Google Play Music is different than Google Podcasts, would be nice to have a field on the Podcast Apps page for Google Podcasts.

**Comment by jamesmontemagno** [comment]
Here are the brand assets https://developers.google.com/search/docs/data-types/images/google_podcasts_brand_assets.zip

**Comment by jamesmontemagno** [comment]
also a link to where you can generate a link for your pod https://search.google.com/devtools/podcast/preview
