### ISSUE TITLE
Metrics for all episodes

### ISSUE THREAD

**Issue by kirkmc1** [firesidelabs/fireside-features#75]
I'd like to be able to see metrics for more than just the ten most recent episodes. I want to know which of my episodes are the most popular. CSV export would also be great to be able to analyze metrics in a spreadsheet, and share them with others (such as sponsors).

**Comment by dan** [comment]
You can currently see metrics for every episode on the Episode's Stats page. I'm not sure if thats what you meant.

**Comment by kirkmc1** [comment]
No, I meant in some more practical list form. For one of my podcasts, I currently have 129 episodes, so that's 9 pages. Ideally, I'd like to see a long list, or perhaps a list from most to least, so I can quickly see which are the most popular episodes. 

> On Nov 2, 2018, at 2:36 PM, Dan Benjamin <notifications@github.com> wrote:
> 
> You can currently see metrics for every episode on the Episode's Stats page. I'm not sure if thats what you meant.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


Best,

Kirk

-----
Me: www.kirkville.com - twitter.com/mcelhearn
The PhotoActive podcast: www.photoactive.co
The Next Track podcast: www.thenexttrack.com
My photos: photos.kirkville.com - instagram.com/mcelhearn
