### ISSUE TITLE
Metrics: weekly and monthly download totals

### ISSUE THREAD

**Issue by kirkmc1** [firesidelabs/fireside-features#76]
The Overall Downloads graph shows a trend line that is indicative, but I'd also like to see how many downloads there are in a week, and/or in a month. And if weekly is available, I'd want to be able to choose which day starts the week; in my case, all my podcasts release on Friday, so that would be the ideal day, but others who release on other days would most likely want their week to start on release day.

**Comment by UAPcast** [comment]
We want this feature too. Any progress on this?

**Comment by dan** [comment]
Range selection will allow for this.

**Comment by UAPcast** [comment]
How do I use range selection? Or is this a new feature that has yet to roll out?
