### ISSUE TITLE
ask user for confirmation of podcast deletion request

### ISSUE THREAD

**Issue by rdmarsh** [firesidelabs/fireside-features#78]
Obviously I'm reluctant to test this!

I deleted a podcast that didn't go ahead and was surprised that there wasn't a confirmation dialogue after I clicked the delete podcast button.

I suggest asking for their password, a confirmation word or sentence (maybe type the podcast title to make sure they're deleting the one they expect) or at least ask the user to confirm that they really meant to click the button (eg "are you sure?")

**Comment by dan** [comment]
There is a confirmation. It opens a dialog box which must be clicked before it goes forward.

The text is "Are you absolutely certain you want to delete this Podcast and its episodes, mp3 files, hosts, and all other associated content?"

This has always been there. 

-Dan

**Comment by rdmarsh** [comment]
Thanks Dan, completely missed that, obviously was too distracted while I'm doing things I should be paying more attention to. Sorry for the unneeded ticket
