### ISSUE TITLE
Episode Templates

### ISSUE THREAD

**Issue by ecec** [firesidelabs/fireside-features#8]
Episode Templates: the ability to predefine text for various fields on the New Episode screen. 

It's common to put the same text in the description, like links to social media, Patreon, etc. It would make it easier if Fireside could put this in automatically for us. Same goes for other fields like the tags and season and possibly title.

**Comment by dan** [comment]
This is built now and should roll out March 19, 2018.

**Comment by ecec** [comment]
I'm looking through the admin pages and don't see where to create this now that it's rolled out.
