### ISSUE TITLE
Add More Podcast Directory Buttons

### ISSUE THREAD

**Issue by seans110** [firesidelabs/fireside-features#81]
Requesting to add these directories to:
Listen Notes - https://www.listennotes.com/podcasts/converge-coffee-sean-sullivan-lwgHuUbiEsL/
Podcaser - https://www.podchaser.com/podcasts/converge-coffee-578606
Podsearch - https://podsearch.com/listing/converge-coffee.html
Tapewrite - https://tapewrite.com/@convergecoffee/
Radio Public - https://radiopublic.com/converge-coffee-6Nkd5o

OR can be other links and we can add button text without needing a logo.
![screen shot 2018-11-01 at 1 15 47 pm](https://user-images.githubusercontent.com/44679469/47867571-44198e00-ddd8-11e8-860b-256a133681b1.png)

**Comment by dan** [comment]
We may be adding Radio Public, but won't be adding the others at this time. You can always add them yourself on the Subscribe Page if you'd like!
