### ISSUE TITLE
Stats- Being able to turn off the stat tracking for imported back catalog so it doesn't skew the averages.

### ISSUE THREAD

**Issue by AngelaFisher** [firesidelabs/fireside-features#83]

**Comment by dan** [comment]
Which averages are you concerned they would skew?

**Comment by AngelaFisher** [comment]
![user error](https://user-images.githubusercontent.com/44704851/47932519-23f8d600-de8f-11e8-8265-0c00fa16ce23.png)

See attachment, this is for User Error which we just brought back with new hosts. The back catalog was imported just before we relaunched so it is skewing these metrics that are readily available.

**Comment by dan** [comment]
This will be resolved in a different way.
