### ISSUE TITLE
Stats: Ability to make stats publically visible per episode

### ISSUE THREAD

**Issue by Scootronic** [firesidelabs/fireside-features#86]
Not necessarily the full stats, but have episodes in the full list of episodes and on their own pages be able to list the total number of times downloaded/listened.

**Comment by Scootronic** [comment]
Options to expose more of the stats publicly could be useful as well. At least at the country level. I feel like anything over any time period other than "All time" wouldn't be needed.

**Comment by mackwic** [comment]
I am against it. Private stats are very healthy for the podcast sector. It force us to look at quality over the quantity.

**Comment by dan** [comment]
I have no plans to add this feature in the near term, primarily because of how we do caching and CDNs, the data would never be up to date.
