### ISSUE TITLE
Show filenames after upload

### ISSUE THREAD

**Issue by UAPcast** [firesidelabs/fireside-features#89]
Previously, the uploader would display the filename of the MP3 and then I could copy/paste that into the episode name field. Now, that no longer occurs and I have to manually populate this field.

More of an issue, however, is that there's no confirmation of which MP3 file was actually uploaded. The previous uploader displayed the name of the file. The new one does not - it merely tells you that it has been successfully uploaded. I have no way of knowing what file I actually uploaded to the service once it's done. It also doesn't tell me the length of the episode after the upload has occurred.

**Comment by dan** [comment]
Sorry about that. This is how the uploader works, though, and it cannot really be changed for you.
