### ISSUE TITLE
Specify RSS Info Separate from Website Info

### ISSUE THREAD

**Issue by jamesmontemagno** [firesidelabs/fireside-features#9]
Hey there! We would really love to specify a different Title that is displayed in the RSS for the podcast then what is displayed on the website. Right now everything is smushed together and it makes it hard to have a nice website, but still fill in details about the podcast. Ideally there would be two sections. 1.) RSS Info and 2.) Website Appearance.

**Comment by dan** [comment]
Can you show me an example (like your URL)?

**Comment by jamesmontemagno** [comment]
So right now on: http://www.thevspot.fm/

Our title is set to "The V Spot: Vegan Podcast", which you can see in the title tag of the site. This will show up on iTunes and other podcast apps, which is great! However, we don't really want it to show up on the main site as the podcast is just "The V Spot". Additionally, we would love to specify a different description for iTunes and for the website.

Right now we have to run this javascript to swap things out for the site:

```
<script type="text/javascript">

    function titleRplc() {
      var headerEl = document.getElementsByTagName("h1")[0];
      if (headerEl !== undefined) {
            headerEl.innerHTML = headerEl.innerHTML.replace(/The V Spot: Vegan Podcast/g, 'The V Spot');
      }
      document.body.innerHTML =  document.body.innerHTML.replace(/The V Spot: Vegan Podcast/g, 'The V Spot');
    }
    
document.addEventListener('DOMContentLoaded', function() {
    titleRplc();
}, false);

</script>
```
