### ISSUE TITLE
Alexa Flash Briefing

### ISSUE THREAD

**Issue by wrestlingandy** [firesidelabs/fireside-features#90]
We're currently using one of our Fireside feeds primarily for an Alexa Flash Briefing. Is it possible to limit our feed to display only 1 item (the most recent published)? Or could we maybe schedule episodes to unpublish? Not sure what would be easier to implement.

Currently Alexa plays the most recent episode first, but then replays the older ones still listed in the feed. We're having to unpublish episodes manually each time.

Thanks in advance! - Andy

**Comment by dan** [comment]
We're working on an Alexa Flash Briefing feature, probably for late Q1/early Q2.

**Comment by wrestlingandy** [comment]
Awesome, thanks Dan! 🙌

**Comment by dan** [comment]
Done.
