### ISSUE TITLE
Prefilled Markdown or HTML link in Share box

### ISSUE THREAD

**Issue by noelrappin** [firesidelabs/fireside-features#92]
The Share tab for episodes is great. I very commonly have to use the title of the episode and the link together.

Any of the following would be great:

a) Included the title of the episode somewhere so that I could copy it from that tab

b) Able to copy a Markdown link of the form `[Title of Episode](episodeURL)`

c) Able to copy an HTML link of the form `<a href="episodeURL">Title of Episode</a>`

**Comment by dan** [comment]
This isn't something we'd be adding to the Share link, as that's reserved for URLs. Isn't this something you can copy from the admin?
