### ISSUE TITLE
Hide Your Hosts Section on Website

### ISSUE THREAD

**Issue by OneJaeAtATime** [firesidelabs/fireside-features#93]
When you have No Hosts selected on an episode or no hosts added to the show, is there a way to hide the Your Hosts field?

**Comment by dan** [comment]
There could be, but how can you have a podcast episode without a host (I'm really asking)?

**Comment by OneJaeAtATime** [comment]
That is a good point. I was thinking from a simplicity standpoint of if someone forgot to fill in the details, it wouldn’t show to be minimalistic.
