### ISSUE TITLE
Embed Autoplay Feature

### ISSUE THREAD

**Issue by mechamjoseph** [firesidelabs/fireside-features#96]
If I could pass in a parameter to make the embed code autoplay on load that would be fantastic! For example, here is how you set an embedded YouTube video to autoplay: `src="https://youtu.be/oUweXAt5OF4?autoplay=1"`

Thanks!

**Comment by dan** [comment]
Good idea.

**Comment by dan** [comment]
Sorry, but after some extensive research, I've decided to table this feature.
