### ISSUE TITLE
Metrics: Ignore pre-release downloads

### ISSUE THREAD

**Issue by noelrappin** [firesidelabs/fireside-features#97]
I love the new metrics package, but I have one thing that might be worth addressing:

In the episode lifecycle page, most of my episodes have hundreds of day one downloads, but some of my episodes have just one or two downloads on "day 1", because we had them in preview and the host or guest downloaded them.

It all washes out eventually so it's not a big deal, but I wonder if day 1 could be counted from first public release rather than first download?

**Comment by mamstergrub** [comment]
Aha! Most of my episodes have 1 download on Day 1, and I figured it was just waiting for an index to finish building or something. This would explain it. Seconded!

**Comment by dan** [comment]
I've done this for you (and the others who have requested it via support ticket).

Now I can await the support tickets and feature suggestions asking why the downloads on the first day of the graph don't match the day 1 numbers ...

**Comment by mamstergrub** [comment]
Excellent, this looks perfect--thank you!
